from app.schemas.user import (
    UserCreate,
    UserLogin,
    UserResponse,
    Token,
    TokenData,
    OrganizationCreate,
    OrganizationResponse,
)

from app.schemas.campaign import (
    CampaignCreate,
    CampaignUpdate,
    CampaignResponse,
    CampaignBrief,
    CampaignStats,
    CampaignAddRecipients,
    CampaignRecipientResponse,
    RecipientPreview,
    CampaignSendRequest,
    CampaignSendResponse,
    MessageCreate,
    MessageResponse,
    MessageBrief,
    MessageEventResponse,
    EmailSendRequest,
    EmailSendResponse,
    PaginatedCampaigns,
    PaginatedMessages,
)

from app.schemas.contact import (
    ContactCreate,
    ContactUpdate,
    ContactResponse,
    ContactBrief,
    ContactListCreate,
    ContactListUpdate,
    ContactListResponse,
    ContactListWithContacts,
    ContactImportMapping,
    ContactImportRequest,
    ContactImportResult,
    ContactBulkAddToList,
    ContactBulkDelete,
    ContactBulkUpdateStatus,
    ContactSearchParams,
    PaginatedContacts,
    PaginatedContactLists,
)

from app.schemas.template import (
    TemplateCreate,
    TemplateUpdate,
    TemplateResponse,
    TemplateBrief,
    TemplatePreviewRequest,
    TemplatePreviewResponse,
    TemplateVariableInfo,
    TemplateValidationResult,
    PaginatedTemplates,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenData",
    "OrganizationCreate",
    "OrganizationResponse",
    # Campaign schemas
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignResponse",
    "CampaignBrief",
    "CampaignStats",
    "CampaignAddRecipients",
    "CampaignRecipientResponse",
    "RecipientPreview",
    "CampaignSendRequest",
    "CampaignSendResponse",
    "MessageCreate",
    "MessageResponse",
    "MessageBrief",
    "MessageEventResponse",
    "EmailSendRequest",
    "EmailSendResponse",
    "PaginatedCampaigns",
    "PaginatedMessages",
    # Contact schemas
    "ContactCreate",
    "ContactUpdate",
    "ContactResponse",
    "ContactBrief",
    "ContactListCreate",
    "ContactListUpdate",
    "ContactListResponse",
    "ContactListWithContacts",
    "ContactImportMapping",
    "ContactImportRequest",
    "ContactImportResult",
    "ContactBulkAddToList",
    "ContactBulkDelete",
    "ContactBulkUpdateStatus",
    "ContactSearchParams",
    "PaginatedContacts",
    "PaginatedContactLists",
    # Template schemas
    "TemplateCreate",
    "TemplateUpdate",
    "TemplateResponse",
    "TemplateBrief",
    "TemplatePreviewRequest",
    "TemplatePreviewResponse",
    "TemplateVariableInfo",
    "TemplateValidationResult",
    "PaginatedTemplates",
]
